# Generated by Django 3.2.4 on 2021-09-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='source',
        ),
        migrations.AlterField(
            model_name='reviewquote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.quote'),
        ),
    ]
