# Generated by Django 3.2.7 on 2021-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_source_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
