# Generated by Django 3.2.7 on 2021-09-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_source_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
