# Generated by Django 3.2.7 on 2021-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_reviewquote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
