# Generated by Django 3.2.7 on 2021-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_quote_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
