# Generated by Django 3.2.7 on 2021-09-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_source_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewquote',
            old_name='content',
            new_name='review',
        ),
    ]
